---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-app
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below 
  nfs:
    server: 192.168.11.3
    path: /app

