---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 5Gi
