---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-docker-registry
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 500Gi
